# Force correct content types
[[headers]]
for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"

[[headers]]
for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"

# Allow indexing site-wide
[[headers]]
for = "/*"
  [headers.values]
  X-Robots-Tag = "all"
