# Sitemaps & robots: correct type + avoid stale cache
[[headers]]
for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  Cache-Control = "no-cache"

[[headers]]
for = "/sitemap_index.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
  Cache-Control = "no-cache"

[[headers]]
for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain; charset=utf-8"
  Cache-Control = "no-cache"

# Ensure indexing is allowed everywhere
[[headers]]
for = "/*"
  [headers.values]
  X-Robots-Tag = "all"
